spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_app?createDatabaseIfNotExist=true
    username: root
    password: M3lesh_672001
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: ahmad
      password: ahmad